### ISSUE TITLE
Header Tweaks

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency-xyz#76]
Header needs to be tweaked slightly:

- [x] Update Style Guide Header and Release
- [x] Left align the logo
- [x] Right align the nav links
- [x] Slightly smaller padding between the nav links
- [x] Update Style Guide Library in xyz
- [x] Able to set the logo to be wrapped in an anchor tag and linked

Figma: https://www.figma.com/design/DVjqjKrUWwFzgZzXCsVdGv/Frequency_Marketing-Site_?node-id=2210-1385&node-type=canvas&t=JvEcfiRCowfKicGx-0

![Image](https://github.com/user-attachments/assets/7d7f7946-57cb-4abc-a935-06daad2babfd)

**Comment by wilwade** [comment]
@claireolmstead I added one more thing to the list if you haven't fully started "Able to link the logo" As I keep trying to click on it to go to a place.

**Comment by claireolmstead** [comment]
@wilwade I added an href to the header so all you have to do is add that in. wasn't sure if we ever wanted to link externally (seems weird) so not sure if we also need a target or something. Since the release isn't cut, I didn't update the version in the .xyz site.
